axe-api/axe-api

src/core/Model.js, src/resolvers/setExpressRoutes.js
Hello @ozziest I hope, this is correct😅.
=> Update on `ignore()` method

CHANGELOG.md, package.json, src/core/QueryParser.js, src/resolvers/checkModelColumns.js, tests/unit/core/queryParser.spec.js
=> Fixed some bugs

package-lock.json, package.json, src/core/Model.js, src/core/QueryParser.js, src/handlers/helpers.js, src/resolvers/getModelTree.js, src/resolvers/setExpressRoutes.js
- Fixed #69 
- Fixed #70 
- Fixed #71 
- Fixed #72
=> Fixed bugs

CHANGELOG.md, package-lock.json, package.json, src/Server.js
=> Fixed cors bug

.github/PULL_REQUEST_TEMPLATE.md
=> Added pull request templates

.github/workflows/auto-tag.yml
This is a PR to provide auto-tagging action.
I created this PR because of automationç
=> Added autotag workflow

.github/workflows/test-integration.yml, .github/workflows/test-unit.yml, CHANGELOG.md, package.json, src/handlers/store.js, src/resolvers/setExpressRoutes.js, tests/integrations/package-lock.json, tests/integrations/scenarios/app/Models/Category.js, tests/integrations/scenarios/app/Models/Unit.js, tests/integrations/scenarios/app/Models/User.js, tests/integrations/scenarios/app/init.js, tests/integrations/scenarios/migrations/20211028142426_Units.js, tests/integrations/scenarios/migrations/20211028142427_Categories.js, tests/integrations/scenarios/tests/00-initialization.spec.js, tests/integrations/scenarios/tests/01-user.spec.js, tests/integrations/scenarios/tests/02-post.spec.js, tests/integrations/scenarios/tests/05-models.spec.js, tests/integrations/scenarios/tests/helper.js
=> Fixed #117

CHANGELOG.md, package.json, src/constants.js, src/core/Model.js, src/handlers/all.js, src/handlers/index.js, src/handlers/patch.js, src/resolvers/setExpressRoutes.js, tests/integrations/scenarios/app/Models/Category.js, tests/integrations/scenarios/app/Models/User.js, tests/integrations/scenarios/tests/01-user.spec.js, tests/integrations/scenarios/tests/02-post.spec.js, tests/integrations/scenarios/tests/05-models.spec.js, tests/integrations/scenarios/tests/helper.js
- [#110](https://github.com/axe-api/axe-api/issues/110)
- [#106](https://github.com/axe-api/axe-api/issues/106)
=> Added new features and fixed bugs

CHANGELOG.md, package-lock.json, package.json, src/handlers/paginate.js, src/handlers/show.js
Fixed the calling `onBeforePaginate` and `onBeforeShow` hooks bug.
=> Fixed the calling `onBeforePaginate` and `onBeforeShow` hooks bug.

.github/workflows/test-integration.yml, .gitignore, .npmignore, package-lock.json, package.json, scripts/dev-kit-install.sh, scripts/dev-kit-remove.sh, scripts/test-mysql5.sh, scripts/test-mysql57.sh, scripts/test-mysql8.sh, scripts/test-postgres.sh, src/Builders/RouterBuilder.ts, tests/integrations/docker-compose.mysql57.yml, tests/integrations/docker-compose.mysql8.yml
This PR contains 'dev-kit' scripts for easy installation and deletion. 
https://github.com/axe-api/docs/issues/40
=> Added dev-kit scripts

readme.md
=> Fixed domain

.github/workflows/test-dev-kit.yml, scripts/dev-kit-install.sh, scripts/dev-kit-remove.sh
https://github.com/axe-api/axe-api/issues/130
Added special test cases.
=> Fixed dev-kit installation bug

.github/workflows/auto-tag.yml, .github/workflows/npm-publish.yml, .github/workflows/test-dev-kit.yml, .github/workflows/test-integration.yml, .github/workflows/test-unit.yml
We now also support newer node js versions  🎉
Close #152 
Github Actions
- [ x] New feature (non-breaking change which adds functionality)
=> add-new-nodejs-version-support

src/Services/SchemaValidatorService.ts, src/constants.ts
Now user can't use the keywords we reserved for the framework
=> Reserved keys for framework

.github/workflows/test-dev-kit.yml, .github/workflows/test-integration.yml, .github/workflows/test-unit.yml
=> Fixed #174

scripts/test-mysql57.sh, scripts/test-mysql8.sh, scripts/test-postgres.sh
https://github.com/axe-api/axe-api/issues/219
=> Fixed #219

.github/workflows/test-dev-kit.yml, .github/workflows/test-integration.yml, .github/workflows/test-unit.yml
=> Issue 174 node20

scripts/dev-kit-install.js
Fixed critical Sonar issues.
The reported lines are false positives.
=> Sonar warnings

CODE_OF_CONDUCT.md, CONTRIBUTING.MD, readme.md
https://github.com/axe-api/axe-api/issues/186
=> Fixed #186

src/Handlers/DestroyHandler.ts, src/Handlers/ForceDestroyHandler.ts, src/Services/QueryService.ts, tests/integrations/scenarios/tests/01-user.spec.js, tests/integrations/scenarios/tests/02-post.spec.js, tests/integrations/scenarios/tests/06-soft-delete.spec.js, tests/integrations/scenarios/tests/helper.js, tests/unit/Services/QueryService.spec.ts
- https://github.com/axe-api/axe-api/issues/252
- Fixed wrong HTTP status code in resource delete
=> Fixed #252

.github/workflows/test-integration.yml, package.json, scripts/test-cockroach.sh, scripts/test-mariadb.sh, scripts/test-postgres.sh, scripts/test-sqlite.sh, src/Handlers/Helpers.ts, src/constants.ts, tests/integrations/.gitignore, tests/integrations/docker-compose.cockroach.yml, tests/integrations/docker-compose.mariadb.yml, tests/integrations/knexfile.js, tests/integrations/package-lock.json, tests/integrations/package.json, tests/integrations/scenarios/app/config.ts, tests/integrations/scenarios/tests/helper.js, tests/integrations/serve-options.json, tests/integrations/src/Helpers.js
https://github.com/axe-api/axe-api/issues/178
=> Fixed #178

package-lock.json, package.json, scripts/publish.sh, src/Builders/ModelTreeBuilder.ts, src/Builders/RouterBuilder.ts, src/Enums.ts, src/Handlers/RequestHandler.ts, src/Helpers.ts, src/Interfaces.ts, src/Phases/Delete/QueryPhase.ts, src/Phases/ForceDelete/PreparePhase.ts, src/Phases/ForceDelete/QueryPhase.ts, src/Phases/Patch/PrepareActionPhase.ts, src/Phases/Show/FetchPhase.ts, src/Phases/Single/GetPhase.ts, src/Phases/Store/PreparePhase.ts, src/Phases/Update/PrepareActionPhase.ts, src/Resolvers/ModelResolver.ts, src/Resolvers/VersionResolver.ts, src/Server.ts, src/Services/APIService.ts, src/Services/App.ts, src/Services/AxeResponse.ts, src/Services/LogService.ts, src/Services/SchemaValidatorService.ts, src/Services/URLService.ts, src/constants.ts, tests/integrations/package-lock.json
https://github.com/axe-api/axe-api/issues/227
=> Fixed #227

tests/integrations/package-lock.json, tests/integrations/scenarios/app/config.ts, tests/unit/Builders/ModelTreeBuilder.spec.ts, tests/unit/Builders/RouteBuilder.spec.ts, tests/unit/Resolvers/ModelResolver.spec.ts
https://github.com/axe-api/axe-api/issues/227
=> Fixed logger tests

.prettierignore, src/Builders/RouterBuilder.ts, src/Handlers/AllHandler.ts, src/Handlers/DestroyHandler.ts, src/Handlers/ForceDestroyHandler.ts, src/Handlers/Helpers.ts, src/Handlers/PaginateHandler.ts, src/Handlers/PatchHandler.ts, src/Handlers/ShowHandler.ts, src/Handlers/StoreHandler.ts, src/Handlers/UpdateHandler.ts, tests/integrations/package-lock.json
https://github.com/axe-api/axe-api/issues/168
=> Fixed #168

CHANGELOG.md, package-lock.json, package.json, tests/integrations/package-lock.json
Security updates
- https://github.com/axe-api/axe-api/security/dependabot/40
- https://github.com/axe-api/axe-api/security/dependabot/41
=> Security fix

.github/workflows/auto-tag.yml, CHANGELOG.md, package-lock.json, package.json, src/Phases/Store/ResultPhase.ts, src/constants.ts
https://github.com/axe-api/axe-api/issues/279
=> Fixed #279

CHANGELOG.md, package-lock.json, package.json, src/Handlers/Helpers.ts, src/Middlewares/RateLimit/RedisAdaptor.ts, src/Phases/GetCachePhase.ts, src/Resolvers/ModelResolver.ts, tests/integrations/package-lock.json
https://github.com/axe-api/axe-api/issues/281
=> Fixed #281

src/Services/URLService.ts, tests/integrations/package-lock.json
https://github.com/axe-api/axe-api/issues/308
=> Fixed #308

src/Resolvers/ModelResolver.ts, src/Types.ts
SchemaInspectorFuction was renamed as SchemaInspectorFu(**n**)ction :)
- src/Types.ts
- src/Resolvers/ModelResolver.ts
=> renames to SchemaInspectorFunction

src/Phases/All/FetchPhase.ts, tests/integrations/package-lock.json, tests/integrations/scenarios/tests/05-models.spec.js
https://github.com/axe-api/axe-api/issues/330
=> Fixed #330

CHANGELOG.md, package-lock.json, package.json, src/Builders/ModelTreeBuilder.ts, src/Interfaces.ts, src/Model.ts, src/constants.ts, tests/unit/Builders/ModelTreeBuilder.spec.ts
https://github.com/axe-api/axe-api/issues/148
=> Added disabling auto-route creation for has-many relations feature

package-lock.json, package.json, src/Interfaces.ts, tests/integrations/package-lock.json
https://github.com/axe-api/axe-api/issues/390
=> Fixed #390

bin/axe, cli/Commands/Hooks/CreateHooksCommand.js, cli/Commands/Models/CreateModelCommand.js, cli/Commands/NewCommand.js, cli/dev.js, cli/helpers.js, cli/index.js, package-lock.json, package.json, src/Interfaces.ts
https://github.com/axe-api/axe-api/issues/143
=> Fixed #143

docs/docs/.vitepress/config.js, docs/docs/rest-api.md
=> Added Rest API page to docs

src/Server.ts, tests/integrations/package-lock.json, tests/integrations/scenarios/app/config.ts, tests/integrations/scenarios/app/v1/Models/Feed.ts, tests/integrations/scenarios/tests/10-rate-limit.spec.js
https://github.com/axe-api/axe-api/issues/563
=> #563 - Rate limit doesn't work

src/Builders/SwaggerBuilder.ts, src/Interfaces.ts, src/Services/LimitService.ts, tests/integrations/package-lock.json
- https://github.com/axe-api/axe-api/issues/602
- https://github.com/axe-api/axe-api/issues/603
- https://github.com/axe-api/axe-api/issues/604
=> Docs issues
